name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          port: 22
          user: ${{ secrets.STAGING_USER }}
          # ssh remote password
          pass: ${{ secrets.STAGING_PASSWORD }}
          script: |
            cd /var/www/html/melanoma-detection
            git pull
            composer install
            php artisan migrate
            php artisan key:gen
            php artisan config:clear
            php artisan cache:clear